name: Generate Dummy Trees

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]
  workflow_dispatch:

env:
  DUMP_URL: # Git URL of the Dump
  
  # Github
  GITHUB_USERNAME: Sushrut1101
  GITHUB_EMAIL: guptasushrut@gmail.com
  GIT_TOKEN: ${{ secrets.GH_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Configuring Git...
         run: |
              git config --global user.name $GITHUB_USERNAME
              git config --global user.email $GITHUB_EMAIL
